### ISSUE TITLE
Sync is unsubscribing from communities that I want to keep.

### ISSUE THREAD

**Issue by CharlieDestroyerOfTacos** [gusVLZ/lemmy_handshake#16]
I have 4 different Lemmy accounts on 4 separate instances. If I run handshake to sync all 4 instances, handshake randomly unsubscribes me from several of my favorites categories.

There should be a setting in the app to tell Handshake that I do not want to unsubscribe from ANY communities, only copy between the instances.

**Comment by gusVLZ** [comment]
I'll soon add a settings view to change time between syncs, notifications and I'll add this option too

**Comment by gusVLZ** [comment]
just added the setting
