### ISSUE TITLE
I lost more than 100 communities from my lemm.ee instance.

### ISSUE THREAD

**Issue by kratoz29** [gusVLZ/lemmy_handshake#19]
And I am not even sure which were they :/

I attempted to sync lemm.ee with my account from lemmy.fmhy.net and it synced about 553 communities, but my main account at lemm.ee reports 463... And I had like 660 something.

Is there anyway to recover them? Didn't the app did like a backup first? I have no backups of any sort.

**Comment by kratoz29** [comment]
Ok, it keeps unsubscribing me from communities, can I get at least a list of the communities it unsubscribed to re-subscribe manually?

**Comment by gusVLZ** [comment]
Oh shit, so sorry to hear that, this shouldn't happen, I added a settings view and disabled unfollow for default.

I know it stores a list of communities in android/data, it's a db file but I'm not sure it can be open

so sorry again for the throuble

**Comment by kratoz29** [comment]
> Oh shit, so sorry to hear that, this shouldn't happen, I added a settings view and disabled unfollow for default.
> 
> I know it stores a list of communities in android/data, it's a db file but I'm not sure it can be open
> 
> so sorry again for the throuble

No problem, I was able to recover a lot of stuff from previous backups and that, so it took me a little bit to update my subscriptions, I'd like to try this tool again, but to be honest I feel so comfortable with lemm.ee that I haven't bothered with anything else at the moment.
